### ISSUE TITLE
ESLint Error with `recharts` Module Not Found on Local Windows Machine

### ISSUE THREAD

**Issue by CharlesZhao27** [BeeQuantAI/platform_app#3]
### Description
While running the `yarn lint` command on a local Windows machine, I encountered an error suggesting an issue with ESLint configuration or dependency resolution. The specific error points to a problem with the `recharts` module not being found or incorrectly referenced in the project.

### Environment
- **Operating System:** Windows 10
- **Node.js Version:** v20.11.0
- **Yarn Version:** 1.22.19
- **ESLint Version:** 8.57.0
- **TypeScript Version:** 5.4.2
- **Affected Package:** `recharts`

### Command Executed
```bash
yarn lint

Oops! Something went wrong! :(

ESLint: 8.57.0

Error: Cannot find module 'C:\Users\Charles\Desktop\beequant_ai\platform_app\node_modules\recharts\lib\index'. Please verify that the package.json has a valid "main" entry Occurred while linting C:\Users\Charles\Desktop\beequant_ai\platform_app\src\containers\App\App.tsx:5 Rule: "import/no-cycle" at tryPackage (node:internal/modules/cjs/loader:444:19) [...]
```
### Steps to Reproduce
1. Navigate to the project directory.
2. Run `yarn lint`.

### Expected Behavior
The `yarn lint` command should complete without errors, and ESLint should successfully lint the project files.

### Actual Behavior
The linting process exits with an error related to not being able to find the `recharts` module.

### Temporary Solution
Downgrading the TypeScript version resolves the issue, but this is not ideal as it might negatively impact other parts of the project or dependencies.

**Comment by Chris-Wang** [comment]
I've added a guide about how to fix CRLF issue on notion, please check: 
https://www.notion.so/Resolve-Line-Breaks-issue-in-Windows-25923567600e487a85dc2670ec6fd723?pvs=4
